name: 24/7 YouTube Stream 2

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video from Cloud
        env:
          VIDEO_URL_2: ${{ secrets.VIDEO_URL_2 }}
        run: |
          curl -L -o video2.mp4 "$VIDEO_URL_2"

      - name: Start Streaming
        env:
          STREAM_KEY_2: ${{ secrets.STREAM_KEY_2 }}
        run: |
          ffmpeg -re -stream_loop -1 -i video2.mp4 -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY_2"
